services:
  automate_mysql:
    image: mysql:8.0
    container_name: automate_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: axioma
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 27d9IyP3Tyg19WUL8a6T
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
